### ISSUE TITLE
choose graphical framework

### ISSUE THREAD

**Issue by untzag** [Tyler314/BMO#2]
our first step is to choose a graphical framework

we should try out a few of them to compare and contrast, given that we're current inexperienced---we don't even know good questions to ask

options:
- [ ] [qtpy](https://github.com/spyder-ide/qtpy)
- [x] [pygame](https://www.pygame.org/wiki/about)
- [ ] [TkInter](https://wiki.python.org/moin/TkInter)
- [ ] "bare" qt (C++ and QML)
- [ ] gtk (for example, [gtk-rs](https://gtk-rs.org/)
- [ ] [wxWigets](https://wxwidgets.org/)

**Comment by tyler314** [comment]
I vote we use Pygame. From my time using the framework, I have enjoyed it. It's a wrapper for the C++ library SDL which seems to be popular for game development. It's also pretty easy to use, and should serve the purpose of everything we need (image & text display, sprite rendering, graphics, game development for simple BMO video games).
